In [5]:
class Exm:
    '''basic example'''
    a=10
    def Exam():
        return("Example from exam function")
    
print(Exm.a)
print(Exm.Exam())
print(Exm.__doc__)

10
Example from exam function


In [7]:
class factorial:
    def fact(i):
        fac=1
        for i in range(1,i+1):
            fac=fac*i
        return fac
print(factorial.fact(10))
        
        


3628800


In [10]:
class A:
    def perfect(self,a):
        sum=0
        for i in range(1,a):
            if a%i==0:
                sum+=i
        if sum==a:
            return "it is a perfect number"
        else:
            return "not a perfect number"
a=A()
n=int(input("enter number"))
a.perfect(n)
        
    
    


enter number6


'it is a perfect number'

In [11]:
class A:
    def prime(self,a):
        count=0
        for i in range(1,a+1):
            if a%i==0:
                count+=1
        if count==2:
            return "it is a prime number"
        else:
            return "it is not prime number"
a=A()
a.prime(13)
    
    

'it is a prime number'

In [12]:
class Noparacons():
    def __init__(self):
        print("using only self")
    def show(name):
        print("welcome ",name)
np=Noparacons()
np.show()
    

using only self
welcome  <__main__.Noparacons object at 0x000002323A238640>


In [14]:
class Paracons:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def add(abc):
        return abc.a+abc.b
pc=Paracons(10,1)
pc.add()
        
    

11

In [18]:
class Multicons():
    def __init(self):
        print("first cons")
    def __init(self):
        print("from second")
  


TypeError: Multicons() takes no arguments

In [22]:
#single
class A():
    a=1
    def ca():
        return("from parent class")
class B(A):
    b=2
    def cb():
        return("from child class")
obj=B
print(obj.cb())
print(obj.ca())

from child class
from parent class


In [23]:
class A():
    a=1
    def ca():
        return "from parent class"
class B(A):
    b=2
    def cb():
        return "from class B"
class C(B):
    c=2
    def cc():
        return "from class C"
obj=C
print(obj.ca())
print(obj.cb)
print(obj.cc)

from parent class
<function B.cb at 0x000002323A303310>
<function C.cc at 0x000002323A3030D0>


In [29]:
from package.pack2 import Mymath
ob=Mymath(7,5)
ob.add()

TypeError: Mymath() takes no arguments

In [4]:
from package.pack3 import phonenum
phonenumber=(input("enter phone number"))
phonenum(phonenumber)

enter phone number7013327948


TypeError: phonenum() takes 0 positional arguments but 1 was given

In [2]:
import numpy as np
print(np.__version__)



1.19.2


In [3]:
print(np.array([2,4,6,8]))

[2 4 6 8]


In [4]:
data=np.array([[1,2,3,4],[2,4,6,7]])
print(data)

[[1 2 3 4]
 [2 4 6 7]]


In [5]:
a1=np.array([2,4,6,8])
a2=np.array([1,5,9,7])
print("addition of matrix ix",a1+a2)
print("subtraction of matrix is",a1-a2)
print("multiplication of matrix is",a1*a2)

addition of matrix ix [ 3  9 15 15]
subtraction of matrix is [ 1 -1 -3  1]
multiplication of matrix is [ 2 20 54 56]


In [6]:
print(np.shape(data))
print(data.dtype)


(2, 4)
int32


In [14]:
data=np.array([[1.0,2,3.1,4.1],[2.1,4.0,6.5,7.6]])
print(data)
print(data.dtype)

[[1.  2.  3.1 4.1]
 [2.1 4.  6.5 7.6]]
float64


In [7]:
#reshange
data2=np.array([[1,2,3,4],[4,5,6,7]])
print(data2)
data2.reshape(4,2)


[[1 2 3 4]
 [4 5 6 7]]


array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [8]:
print(data2)

[[1 2 3 4]
 [4 5 6 7]]


In [9]:
data2.flatten()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [11]:
np.hstack((a1,a2))

array([2, 4, 6, 8, 1, 5, 9, 7])

In [13]:
np.vstack((a1,a2))

array([[2, 4, 6, 8],
       [1, 5, 9, 7]])

In [17]:
print(data2)
print(data2.mean())
print(data2.std())

[[1 2 3 4]
 [4 5 6 7]]
4.0
1.8708286933869707


In [23]:
print(np.median(data2))
print(np.mod(2,3))

4.0
2


In [25]:
data=np.array([[1,2,3,4],[2,3,4,5]])
print(data)

[[1 2 3 4]
 [2 3 4 5]]


In [27]:
#random numbers
d=np.random.randint(1,30,(3,3))
print(d)

[[12 17 16]
 [20 21 29]
 [ 4 16  1]]


In [28]:
np.random.normal(5,4,10)

array([8.84731411, 4.00740489, 9.03213759, 7.4697789 , 0.04326597,
       7.65005172, 6.27995869, 4.32688538, 5.11588612, 4.47903556])

In [29]:
print(d.min())
print(d.max())

1
29


In [31]:
d.T
print(d)

[[12 17 16]
 [20 21 29]
 [ 4 16  1]]


In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
a=np.array([1,2,3,4])
a2=np.array([3,4,5,6])

print(a)
a.dot(a2)

[1 2 3 4]


50

In [10]:
d1=np.array([1,2,3,4])
np.array([d1,pow(d1,3)])

array([[ 1,  2,  3,  4],
       [ 1,  8, 27, 64]])

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
x=
print(x)

NameError: name 'x' is not defined